export const TRANSACTION_KEYWORDS = [
  'add',
  'spent',
  'income',
  'expense',
  'bought',
  'received',
  'paid',
  'purchase',
  'bill',
  'salary',
  'freelance',
  'bonus',
  'business',
  'investment',
  'rentalIncome',
  'otherIncome',
  'food',
  'lunch',
  'dinner',
  'grocery',
  'rent',
  'utilities',
  'electric',
  'water',
  'entertainment',
  'movie',
  'game',
  'transportation',
  'travel',
  'fuel',
  'shopping',
  'clothes',
  'online',
  'healthcare',
  'doctor',
  'medicine',
  'otherExpense',
];

export const INSIGHT_KEYWORDS = [
  'how much',
  'summary',
  'insight',
  'analysis',
  'report',
  'spending',
  'total',
  'balance',
  'net',
  'sum',
  'history',
  'recent',
  'stats',
  'overview',
  'performance',
  'last',
  'detail',
];

export const CATEGORIES = {
  income: ['business', 'freelance', 'salary', 'investment', 'rentalIncome', 'otherIncome'],
  expense: [
    'food',
    'rent',
    'utilities',
    'entertainment',
    'transportation',
    'shopping',
    'healthcare',
    'otherExpense',
  ],
};

export const CURRENCY = {
  symbol: '$',
  name: 'Dollars',
};

export const REMOVE_KEYWORDS = [
  'remove',
  'delete',
  'undo',
  'clear',
  'cancel',
  'wrong',
  'accidentally',
  'mistake',
];

export const CASUAL_MESSAGES = [
  'ok',
  'okay',
  'thanks',
  'thank you',
  'cool',
  'got it',
  'nice',
  'hi',
  'hello',
  'hey',
  'done',
  '👍',
];

export const SYSTEM_PROMPTS = {
  FINANCE_AI_NAME: 'Finance-AI',
  BASE_RULES: [
    `Use ${CURRENCY.symbol} (${CURRENCY.name}) exclusively.`,
    'Be short and clear. No filler.',
    'NEVER repeat old data unless specifically asked for context.',
    'NEVER generate or imagine data unless asked.',
    'ONLY respond based on user request.',
    'If message is casual (ok, hi, thanks) reply with short acknowledgement.',
    'If transaction: return structured JSON.',
    'If question: answer briefly.',
    'If unclear: ask simple clarification.',
  ],
};
